### ISSUE TITLE
Can a bucket be shared between projects?

### ISSUE THREAD

**Issue by yanivkr** [androidx/gcp-gradle-build-cache#28]
If I have multiple Gradle projects, can I upload them all to a single bucket without issues? If not, is there a way to define a sub folder within a bucket to not have to open multiple buckets?

**Comment by mathjeff** [comment]
I would guess that this would work

Some caveats to consider:

- If multiple projects have the same tasks that declare identical inputs, then one project could reuse cached outputs from another project
  - This could be good if there are no other undeclared inputs (reusing results)
  - This could be bad if there are other undeclared inputs (accidentally getting wrong results)
- If each project has enough cache data it could theoretically be more likely to reach the maximum bucket size
  - I think the bucket size is normally pretty large though so it's probably not an issue
- I think permissions are handled on a per-bucket level
  - I think that would mean anyone that could save a cache entry for one project could save a cache entry for any of the other projects
