### ISSUE TITLE
When will the final version 1.0.0 be released?

### ISSUE THREAD

**Issue by trietbui85** [androidx/gcp-gradle-build-cache#61]
The [1.0.0-beta01](https://github.com/androidx/gcp-gradle-build-cache/releases/tag/1.0.0-beta01) version was released on July 2022 - it means more than 2 years ago.

I don't know what's the blocking issue that prevents the release of final version 1.0.0? Could you share your thought? 🙏

**Comment by liutikas** [comment]
Done. Shipped.
